service:
  name: aienvoy
  host: "0.0.0.0"
  port: 8090
  url: http://localhost:8090
  logLevel: info
  env: dev

# default admin users
admins:
  - email: admin@admin.com
    password: adminadmin

claudeweb:
  token:

bard:
  token:

telegram:
  token:

readease:
  telegramChannel:
  topStoriesCnt: 10

cookiecloud:
  host:
  uuid:
  pass:

midJourney:
  discordUserToken:
  discordBotToken:
  discordServerId:
  discordChannelId:
  discordAppId:
  discordSessionId:
